pizzaeria/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

app_name = 'pizzas'

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'', include(('pizzas.urls', 'pizzas'),
        namespace = 'pizzas')),
]

pizzas/urls.py
"""pizzas의 URL 패턴을 정의한다."""

from django.urls import re_path

from . import views

urlpatterns = [
    #홈페이지
    re_path(r'^$', views.index, name='index'),

    # 피자 종류
    re_path(r'^pizzas/$', views.pizzas, name='pizzas'),
    # 피자에대한 토핑종류
    re_path(r'^pizzas/(?P<pizza_id>\d+)/$', views.topping, name='topping')
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """pizza를 정의한다."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """모델에 관한 정보를 문자열 형태로 변환한다."""
        return self.name

class Topping(models.Model):
    """피자의 토핑에 대해 정의했다."""
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """모델에 관한 정보를 문자열 형태로 변환한다."""
        if self.name[:] > self.name[:50]:
            return self.name[:50] + "..."
        else:
            return self.name[:]

pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """피자 관리 홈페이지"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """pizzz 종류를 나타낸다."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas' : pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def topping(request, pizza_id):
    """pizza종류에 따른 토핑을 나타낸다."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza':pizza, 'toppings': toppings}
    return render(request, 'pizzas/topping.html', context)

pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzaria</a>
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>Welcome to Pizzaria!</p>
  <p>니가 원하는 피자는 이곳에 존재한다!</p>
{% endblock %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:topping' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>No pizzas have added yet.</li>
    {% endfor %}
  </ul>
{% endblock %}

pizzas/templates/pizzas/topping.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.name|linebreaks }}</p>
    </li>
    {% empty %}
      <li>
        There are no toppings for this topping yet.
      </li>
    {% endfor %}
  </ul>

{% endblock %}